---
title: "wifl_acoe_plant_plots"
author: "Patrick D. lorch"
date: "2025-02-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Bring in spreadsheet data

This assumes output from ArcGIS fieldmaps.

Tallys live and dead hits at each meter of height at each meter along a cardinal direction transect.

```{r dataingest}
library(dplyr)
# install.packages(rio)
library(rio)
library(qdapTools)

year = 2023
fp = file.path("C:",
                        "Users",
                        "PatrickLorch",
                        "SSRS",
                        "Southern Sierra Research Station - Documents",
                        "Projects",
                        "WIFL - ACOE",
                        year,
                        "Data",
                        "Veg",
                        "Vegetation_Sampling_2024.xlsx")
data_list = import_list(fp) # , setclass = "tbl", , which = c(1, 2)

names(data_list)
# View(data_list$E_Foliage_Density_4)

e_density = data_list$E_Foliage_Density_4
w_density = data_list$W_Foliage_Density_7
n_density = data_list$N_Foliage_Density_5
s_density = data_list$S_Foliage_Density_6
# names(e_density_24)

base_names = names(e_density)[c(1:6, 107:108)]
hit_col_names = names(e_density)[7:106]
heights = unique(sapply(strsplit(hit_col_names," "), `[`, 2))

e_density_hits_sum = e_density %>%
  select(contains(base_names))
hit_tally = function(df, hght){
  df %>%
    select(contains(hght)) %>%
    t() %>%
    as_tibble() %>%
    qdapTools::mtabulate() %>%
    rename_with(~ paste0(hght, " ", .x, recycle0 = T))
}

e_density_hits_sum = 
  e_density %>%
     mutate(hit_tally(., hght = heights[1]),
            hit_tally(., hght = heights[2]),
            hit_tally(., hght = heights[3]),
            hit_tally(., hght = heights[4]),
            hit_tally(., hght = heights[5]),
            hit_tally(., hght = heights[6]),
            hit_tally(., hght = heights[7]),
            hit_tally(., hght = heights[8]),
            hit_tally(., hght = heights[9]),
            hit_tally(., hght = heights[10])) %>%
  select(contains(base_names), ends_with(c(" X", " D"))) %>%
  rename_with(~ gsub(" X", " live", .x, fixed = T)) %>%
  rename_with(~ gsub(" D", " dead", .x, fixed = T))

write.csv(e_density_hits_sum, paste0("e_density_hits_", year, "_sum.csv"), row.names = F)

w_density_hits_sum = 
  w_density %>%
     mutate(hit_tally(., hght = heights[1]),
            hit_tally(., hght = heights[2]),
            hit_tally(., hght = heights[3]),
            hit_tally(., hght = heights[4]),
            hit_tally(., hght = heights[5]),
            hit_tally(., hght = heights[6]),
            hit_tally(., hght = heights[7]),
            hit_tally(., hght = heights[8]),
            hit_tally(., hght = heights[9]),
            hit_tally(., hght = heights[10])) %>%
  select(contains(base_names), ends_with(c(" X", " D"))) %>%
  rename_with(~ gsub(" X", " live", .x, fixed = T)) %>%
  rename_with(~ gsub(" D", " dead", .x, fixed = T))

write.csv(w_density_hits_sum, paste0("w_density_hits_", year, "_sum.csv"), row.names = F)

n_density_hits_sum = 
  n_density %>%
     mutate(hit_tally(., hght = heights[1]),
            hit_tally(., hght = heights[2]),
            hit_tally(., hght = heights[3]),
            hit_tally(., hght = heights[4]),
            hit_tally(., hght = heights[5]),
            hit_tally(., hght = heights[6]),
            hit_tally(., hght = heights[7]),
            hit_tally(., hght = heights[8]),
            hit_tally(., hght = heights[9]),
            hit_tally(., hght = heights[10])) %>%
  select(contains(base_names), ends_with(c(" X", " D"))) %>%
  rename_with(~ gsub(" X", " live", .x, fixed = T)) %>%
  rename_with(~ gsub(" D", " dead", .x, fixed = T))

write.csv(n_density_hits_sum, paste0("n_density_hits_", year, "_sum.csv"), row.names = F)

s_density_hits_sum = 
  s_density %>%
     mutate(hit_tally(., hght = heights[1]),
            hit_tally(., hght = heights[2]),
            hit_tally(., hght = heights[3]),
            hit_tally(., hght = heights[4]),
            hit_tally(., hght = heights[5]),
            hit_tally(., hght = heights[6]),
            hit_tally(., hght = heights[7]),
            hit_tally(., hght = heights[8]),
            hit_tally(., hght = heights[9]),
            hit_tally(., hght = heights[10])) %>%
  select(contains(base_names), ends_with(c(" X", " D"))) %>%
  rename_with(~ gsub(" X", " live", .x, fixed = T)) %>%
  rename_with(~ gsub(" D", " dead", .x, fixed = T))

write.csv(s_density_hits_sum, paste0("s_density_hits_", year, "_sum.csv"), row.names = F)
  
  
```

